pipeline {
    agent any

    stages {

        stage('Init') {
            steps {
                sh 'pwd'
                sh 'ls -lah'
                sh 'terraform init'
            }
        }

        stage('Plan') {
            steps {
                sh 'terraform plan'
            }
        }

        stage('Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
