pipeline {
    agent any

    environment {
        AWS_CREDS = credentials('aws-jenkins-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Jithendarramagiri1998/snake-game/terraform-eks.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform-eks') {
                    sh '''
                        terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform-eks') {
                    sh '''
                        terraform plan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform-eks') {
                    sh '''
                        terraform apply -auto-approve
                    '''
                }
            }
        }
    }
}
